// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://falnlqkxfodxmphseewf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbG5scWt4Zm9keG1waHNlZXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDY4ODYsImV4cCI6MjA2MDM4Mjg4Nn0.n-llIo3mus55Rwd9McXFsDp8ym7nmUGC0U7I7aFnyGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);